//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public int MaKH { get; set; }

        [Required]
        [StringLength(maximumLength: 100, MinimumLength = 2, ErrorMessage = "Length must be between 2 to 100!")]
        public string TenKH { get; set; }

        [Required]
        //[RegularExpression(@"^/d[10]$", ErrorMessage = "Số điện thoại phải có 10 số")]
        public int sdt { get; set; }

        [StringLength(100)]
        [EmailAddress(ErrorMessage = "Email không hợp lệ")]
        public string email { get; set; }

        [Required]
        [StringLength(100)]
        public string DiaChi { get; set; }

        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required]
        //[StringLength(maximumLength: 20, MinimumLength = 5, ErrorMessage = "Length must be between 5 to 20")]
        [StringLength(20)]
        public string TK { get; set; }

        [Required]
        //[RegularExpression(@"^(?=.*\d).{8,}$", ErrorMessage ="Password must have 1 number")]
        [StringLength(20)]
        public string Pass { get; set; }

        public string Roleuser { get; set; }
        public string Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
