//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DONDATHANGs = new HashSet<DONDATHANG>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public int MaKH { get; set; }
        [Required]
        [StringLength(20)]
        public string TenKH { get; set; }
        [Required]
        public int sdt { get; set; }
        [StringLength(100)]
        public string email { get; set; }
        [Required]
        [StringLength(100)]
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        [Required]
        [StringLength(20)]
        public string TK { get; set; }
        [Required]
        [StringLength(20)]
        public string Pass { get; set; }
        public string Roleuser { get; set; }
        public string Hinh { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DONDATHANG> DONDATHANGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
