//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.CTDATHANGs = new HashSet<CTDATHANG>();
            this.Vourchers = new HashSet<Vourcher>();
            this.YeuThiches = new HashSet<YeuThich>();
        }
    
        public int MaSP { get; set; }

        [StringLength(20, ErrorMessage = " không được vượt quá 20 ký tự.")]
        [Required(ErrorMessage = "Chưa Điền Thông Tin Tên Loại Sản Phẩm.")]
        public string TenSP { get; set; }
        public Nullable<int> GiaSp { get; set; }
        public Nullable<int> GiaGiam { get; set; }

        [Required(ErrorMessage = "Chưa Chọn Hình.")]
        public string Hinh1 { get; set; }
        public string Hinh2 { get; set; }
        public string Hinh3 { get; set; }
        public string Hinh4 { get; set; }

        [Required(ErrorMessage = "Chưa Điền Thông Tin Mô Tả Sản Phẩm.")]
        public string Mota { get; set; }

        [Required(ErrorMessage = "Chưa Điền Thông Tin Thông Số Sản Phẩm.")]
        public string Thongso { get; set; }

        [Required(ErrorMessage = "Chưa Điền Thông Tin Số Lượng Tồn Sản Phẩm.")]
        public Nullable<int> Soluongton { get; set; }
        public int MaLoai { get; set; }
        public Nullable<int> Mamau { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTDATHANG> CTDATHANGs { get; set; }
        public virtual Mau Mau { get; set; }
        public virtual PhanLoai PhanLoai { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vourcher> Vourchers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YeuThich> YeuThiches { get; set; }
    }
}
