//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vourcher
    {
        public int MaKM { get; set; }
        public Nullable<int> Uudai { get; set; }
        public string ThongTinUuDai { get; set; }
        public int MaSP { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
