//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doanphanmem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vourcher
    {
        public int MaKM { get; set; }
        [Required(ErrorMessage = "Chưa Phần Trăm Giảm")]
        public Nullable<int> Uudai { get; set; }
        
        [StringLength(20, ErrorMessage = "Mật khẩu không được vượt quá 20 ký tự.")]
        [Required(ErrorMessage = "Chưa Điền Thông Tin Ưu Đãi.")]
        public string ThongTinUuDai { get; set; }
        public int MaSP { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
